name: 7-zip Test
on:
  push
jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Windows x64
            os: windows-latest
          - name: Linux x64
            os: ubuntu-latest
          - name: macOS x64
            os: macos-latest
    name: Test ${{matrix.platform.name}}
    runs-on: ${{matrix.platform.os}}
    steps:
      - run: 7z