name: Add mask test
on:
  workflow_dispatch:
    inputs:
      password:
        description: "Super secret password"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.event.inputs.password}}
      - run: sleep 30s
      - run: |
          echo ${{github.event.inputs.password}}
          echo ::add-mask::${{github.event.inputs.password}}
          echo ${{github.event.inputs.password}}
      - run: echo ${{github.event.inputs.password}}
