name: ARM Runner Test
on: [workflow_dispatch]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          # If this is just `ubuntu-latest`, GitHub will let our self-hosted runner take this job! (And it seems to prefer it too!)
          # Unfortunately we can't do something like `[ubuntu-latest, X64]` either since the GitHub-hosted runners do not seem to have other labels.
          - os: [pgn-ubuntu-latest, arm64]
    name: Test ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
    - run: uname -a
    - run: dpkg --print-architecture