name: ARM Runner Test
on: [workflow_dispatch]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: ubuntu-arm64-latest
    name: Test ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
    - run: uname -a
    - run: dpkg --print-architecture