name: ARM Runner Test
on: [workflow_dispatch]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # If this is just `ubuntu-latest`, GitHub will let our self-hosted runner take this job! (And it seems to prefer it too!)
          - os: [ubuntu-latest, X64]
          #- os: ubuntu-latest
          - os: [ubuntu-latest, arm64]
    name: Test ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
    - run: uname -a
    - run: dpkg --print-architecture