name: Artifact layers test
on:
  push:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p artifacts/docs/site/
      - run: echo "Artifact from run job1" >> artifacts/docs/site/output.txt
      - run: echo "Artifact from run job1" >> artifacts/docs/site/output1.txt
      - uses: actions/upload-artifact@v4
        with:
          name: Artifact1
          if-no-files-found: error
          path: artifacts/docs/site/
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Artifact from run job2" >> output.txt
      - run: echo "Artifact from run job2" >> output2.txt
      - uses: actions/upload-artifact@v4
        with:
          name: Artifact2
          if-no-files-found: error
          path: '*'
  merge:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Download Artifact1
        uses: actions/download-artifact@v4
        with:
          name: Artifact1
      - run: ls -lR
      - run: cat output.txt
      - run: cat output1.txt
      - name: Download Artifact2
        uses: actions/download-artifact@v4
        with:
          name: Artifact2
      - run: ls -lR
      - run: cat output.txt
      - run: cat output1.txt
      - run: cat output2.txt
