name: Bonsai Matrix Test
on:
  workflow_dispatch:
  pull_request:
jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Windows x64
            os: windows-latest
            rid: win-x64
          - name: Linux x64
            os: ubuntu-latest
            rid: linux-x64
        configuration: ['Debug', 'Release']
        include:
          # Create packages and installer from Windows Release x64
          - platform:
              rid: win-x64
            configuration: Release
            create-packages: true
            create-installer: true
          # Build dummy packages to determine which changed
          - platform:
              name: Previous Dummy
              os: ubuntu-latest
              rid: linux-x64
            skip-tests: true
            dummy-build: true
            configuration: Release
          - platform:
              name: Next Dummy
              os: ubuntu-latest
              rid: linux-x64
            skip-tests: true
            dummy-build: true
            configuration: Release
    name: ${{matrix.platform.name}} ${{matrix.configuration}}
    runs-on: ${{matrix.platform.os}}
    # Do not bother with dummy builds for pull requests
    if: github.event_name != 'pull_request' || matrix.dummy-build != true
    steps:
      - name: Pack
        id: pack
        if: matrix.create-packages
        run: echo dotnet pack --no-build --configuration ${{matrix.configuration}}

      # ----------------------------------------------------------------------- Test
      - name: Test
        if: matrix.skip-tests != true
        run: echo dotnet test --no-restore --no-builds --configuration ${{matrix.configuration}} --verbosity normal
