name: Bonsai Matrix Test
on:
  workflow_dispatch:
  pull_request:
jobs:
  create-build-matrix:
    name: Create Build Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: steps.create-matrix.outputs.matrix
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Create Build Matrix
        id: create-matrix
        run: python .github/workflows/bonsai-matrix-build.py

  print-matrix-json:
    needs: create-build-matrix
    runs-on: ubuntu-latest
    steps:
      - run: echo $MATRIX
        env:
          MATRIX: ${{fromJSON(needs.create-build-matrix.outputs.matrix)}}
    
  build-and-test:
    needs: create-build-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.create-build-matrix.outputs.matrix)}}
    name: ${{matrix.platform.name}} ${{matrix.configuration}}
    runs-on: ${{matrix.platform.os}}
    steps:
      - name: Pack
        id: pack
        if: matrix.create-packages
        run: echo dotnet pack --no-build --configuration ${{matrix.configuration}}

      # ----------------------------------------------------------------------- Test
      - name: Test
        if: matrix.skip-tests != true
        run: echo dotnet test --no-restore --no-builds --configuration ${{matrix.configuration}} --verbosity normal
