name: Build Project
on: [push, workflow_dispatch, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_GENERATE_ASPNET_CERTIFICATE: 0
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: dotnet pack --configuration Release --no-build
    - uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: artifacts/package/release/*.nupkg
