# Verdict: The caching service handles this silently
# The "late" job (Platform B in this case) will quietly print the following message in the post step for actions/cache:
# > Failed to save: Unable to reserve cache with key test-key, another job may be creating this cache.
name: Test actions/cache race handling
on:
  push:
  workflow_dispatch:
jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Platform A
            os: ubuntu-latest
            sleep: 1
          - name: Platform B
            os: ubuntu-latest
            sleep: 10
    name: Test setup-bonsai on ${{matrix.platform.name}}
    runs-on: ${{matrix.platform.os}}
    steps:
      - uses: actions/cache@v4
        id: cache
        with:
          path: test.txt
          key: test-key
      - if: steps.cache.outputs.cache-hit != 'true'
        run: echo Hello, world! | tee test.txt
      - run: cat test.txt
      - run: sleep ${{matrix.platform.sleep}}
