name: Run step even with fail test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: This command will succeed
      id: will-succeed
      run: true
    - name: This command will fail
      id: will-fail
      run: true
    - name: Runs even when there's a fail
      id: steps.will-succeed.outcome == 'success' && always()
      run: echo "will-succeed was successful!"
    - name: Shouldn't ever run
      id: steps.will-fail.outcome == 'success' && always()
      run: echo "will-fail was successful!"
