name: Complex Matrix Test
on:
  push:
jobs:
  multiple-additions:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest']
        configuration: ['Debug', 'Release']
        include:
          - os: windows-latest
            name: Windows
          - os: ubuntu-latest
            name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Print matrix variables
        run: |
          echo ${{matrix.os}}
          echo ${{matrix.configuration}}
          echo ${{matrix.name}}
  objects:
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Windows
            runs-on: windows-latest
          - name: Linux
            runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Print matrix variables
        run: |
          echo ${{matrix.os.name}}
          echo ${{matrix.os.runs-on}}
  objects-with-addition:
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Windows
            runs-on: windows-latest
          - name: Linux
            runs-on: ubuntu-latest
        include:
          - os:
              runs-on: ubuntu-latest
            create-packages: true
    runs-on: ubuntu-latest
    steps:
      - name: Print matrix variables
        run: |
          echo ${{matrix.os.name}}
          echo ${{matrix.os.runs-on}}
          echo ${{matrix.create-packages}}
  biohazrd-not-working:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Windows
            architecture: x64
            runs-on: windows-latest
          - name: Linux
            architecture: x64
            runs-on: ubuntu-latest
        configuration: ['Debug', 'Release']
        include:
          # Linux Release x64 builds create packages (if applicable)
          - platform:
              runs-on: ubuntu-latest
            configuration: Release
            create-packages: true
    runs-on: ubuntu-latest
    steps:
      - name: Print matrix variables
        run: |
          echo platform.name: '${{matrix.platform.name}}'
          echo platform.architecture: '${{matrix.platform.architecture}}'
          echo platform.runs-on: '${{matrix.platform.runs-on}}'
          echo configuration: '${{matrix.configuration}}'
          echo create-packages: '${{matrix.create-packages}}'
      - name: Create packages 1
        if: matrix.create-packages
        run: echo Beep boop I am NuGet packer
      - name: Create packages 2
        if: matrix.create-packages == 'true'
        run: echo Beep boop I am NuGet packer
