name: Conditional job
on:
  workflow_dispatch:
    inputs:
      will_run_second_job:
        description: "Run second job?"
        default: "false"
jobs:
  job_one:
    runs-on: ubuntu-latest
    outputs:
      second-job-enabled: steps.second-job-check.outputs.second_job_enabled
    steps:
      - name: Second job check
        id: second-job-check
        run: echo "::set-output name=second_job_enabled::${{github.event.inputs.will_run_second_job}}"
  two:
    runs-on: ubuntu-latest
    needs: job_one
    if: needs.job_one.outputs.second-job-enabled == 'true'
    steps:
      - run: echo "Second job ran!"
