name: Conditional job
on:
  workflow_dispatch:
    inputs:
      will_run_second_job:
        description: "Run second job?"
        default: "false"
jobs:
  one:
    runs-on: ubuntu-latest
    outputs:
      second_job_enabled: ${{steps.second-job-check.outputs.second_job_enabled}}
    steps:
      - name: Second job check
        id: second-job-check
        run: echo "::set-output name=second_job_enabled::${{github.event.inputs.will_run_second_job}}"
  two:
    runs-on: ubuntu-latest
    needs: one
    if: needs.one.outputs.second_job_enabled == 'true'
    steps:
      - run: echo "Second job ran!"