name: Dump GITHUB_EVENT_PATH
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      will_publish_packages:
        description: "Test input"
        default: "Hello, world!"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        ls /home/runner/work/_temp/_github_workflow/
        echo github.event_path = ${{github.event_path}}
        echo github.event_name = ${{github.event_name}}
        echo github.ref = ${{github.ref}}
        echo GITHUB_EVENT_PATH = "'$GITHUB_EVENT_PATH'"
        cat $GITHUB_EVENT_PATH
