name: Empty matrix test
on:
  push
jobs:
  empty-matrix:
    strategy:
      fail-fast: false
      matrix: ${{fromJson('{}')}}
    name: Job with empty matrix
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
  something-else:
    needs: [ empty-matrix ]
    name: Something else after the empty job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Something else!"
