name: Environment Variable Test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    env:
      TEST_ENVIRONMENT_VARIABLE: Test
      TEST_2: ${{github.workspace}}\test
      TRUE_VAR: true
    steps:
    - name: Test
      run: echo Hello $Env:TEST_ENVIRONMENT_VARIABLE ! $Env:TEST_2 ! $Env:TRUE_VAR World
