name: Test friendly matrix names
on: [push, workflow_dispatch]
jobs:
  'Build Matrix':
    strategy:
      fail-fast: false
      matrix:
        name: ['Windows x64', 'Linux x64', 'Linux ARM64']
    runs-on: ubuntu-latest
    name: ${{matrix.name}}
    steps:
      - run: echo "Hello, world!"
  depends-on-build-matrix:
    needs: 'Build Matrix'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello!"