# https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson
name: fromJSON test
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - id: set-matrix
        #run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
        #run: python .github/workflows/fromjson-test.py
        run: python .github/workflows/bonsai-matrix-build.py
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      #- run: echo "Matrix - Project ${{ matrix.project }}, Config ${{ matrix.config }}"
      - run: echo "Matrix - ${{matrix.platform.name}} ${{matrix.configuration}}"
