name: Get LLVM SHA1
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Get Python version
      shell: python
      run: |
        import sys
        print(sys.version)
    - name: Get Sha1 of LLVM
      id: llvm
      run: python .github/workflows/get-llvm-revision.py
    - name: Test
      run: echo "LLVM_SHA1='${{steps.llvm.outputs.sha1}}'"
