name: install-sccache.py test
on: [workflow_dispatch, push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install sccache
      run: python .github/workflows/install-sccache.py
    - name: Verify
      shell: bash
      run: |
        echo "SCCACHE_DIR='$SCCACHE_DIR'"
        echo ::group::ls
        ls -lRh build-sccache
        echo ::endgroup::
        sccache || true
