name: List all MSVC versions
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: List all versions
      run: python .github/workflows/list-all-msvc-versions.py
