name: Restricted Environment Test (Matrix)
on: [workflow_dispatch]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            environment:
          - os: ubuntu-18.04
            environment: "environment: TestEnvironment"
    name: Test Job - ${{matrix.os}} (${{matrix.environment}})
    runs-on: ubuntu-latest
    ${{matrix.environment}}
    steps:
      - name: Do the thing
        run: echo "Hello, world!"
