name: Test Mochi.PhysX Build Matrix
on: [push, workflow_dispatch]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        rid: [win-x64, linux-x64, linux-arm64, osx-x64]
        configuration:
          - name: Debug
            id: debug
          - name: Checked
            id: checked
          - name: Profile
            id: profile
          - name: Release
            id: release
        include:
          - rid: win-x64
            name: Windows x64
            os: windows-latest
            build-command: ./build.cmd
            physx-install-path: external/PhysX/physx/install/Mochi.PhysX.Windows.x64/
          - rid: linux-x64
            name: Linux x64
            os: ubuntu-latest
            build-command: ./build.sh
            physx-install-path: external/PhysX/physx/install/Mochi.PhysX.Linux.x64/
          - rid: linux-arm64
            name: Linux ARM64
            os: ubuntu-arm64-latest
            build-command: ./build.sh
            physx-install-path: external/PhysX/physx/install/Mochi.PhysX.Linux.ARM64/
          - rid: osx-x64
            name: macOS x64
            os: macos-10.15
            build-command: ./build.sh
            physx-install-path: external/PhysX/physx/install/Mochi.PhysX.macOS.x64/
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: |
          echo 'Name: "${{matrix.name}}"'
          echo 'Configuration Name: "${{matrix.configuration.name}}"'
          echo 'Configuration ID: "${{matrix.configuration.id}}"'
          echo 'RID: "${{matrix.rid}}"'
          echo 'OS: "${{matrix.os}}"'
          echo 'Build Command: "${{matrix.build-command}}"'
          echo 'PhysX Install Path: "${{matrix.physx-install-path}}"'
