name: Needs skipped
on:
  workflow_dispatch:
    inputs:
      should_fail:
        description: "Should fail?"
        default: "false"
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Step
        run: echo "Hello, world!"
      - run: sleep 10
      - name: Fail
        if: github.event.inputs.should_fail == 'true'
        run: false
  two:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Step
        run: echo "Empty world."
  three:
    runs-on: ubuntu-latest
    needs: [one, two]
    # This one runs only when `one` fails (and two being skipped does not suppress it)
    if: failure()
    steps:
      - name: Step
        run: echo "I am the last step"
  three2:
    runs-on: ubuntu-latest
    needs: [one, two]
    if: ${{!cancelled() && !failure()}}
    steps:
      - name: Step
        run: echo "I am the last step"
  three3:
    runs-on: ubuntu-latest
    needs: [one, two]
    # ⚠ This one will run even if the workflow was cancelled
    if: ${{!failure()}}
    steps:
      - name: Step
        run: echo "I am the last step"
  three4:
    runs-on: ubuntu-latest
    needs: [one, two]
    if: |
      !cancelled()
      && needs.one.result == 'success'
      && contains('success skipped', needs.two.result)
    steps:
      - name: Step
        run: echo "I am the last step"
  three5:
    runs-on: ubuntu-latest
    needs: [one, two]
    # ⚠ This will run even if `one` fails!
    if: ${{!cancelled()}}
    steps:
      - name: Step
        run: echo "I am the last step"
  # This one gets skipped transitively
  vanilla:
    runs-on: ubuntu-latest
    needs: [one, two]
    steps:
      - name: Step
        run: echo "I am the last step"