name: Release Event Test
on:
  release:
    # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release
    # Seems `created` doesn't work here or it's not what I think it is
    # -- Oh!
    # > Note: The release event is not triggered for draft releases.
    # Emphasis on ****release event****, I read this as meaning to be the "released" type.
    #####################
    # Edited works!
    # Not sure how to trigger unpublished...
    # Deleted works
    # Not sure what prereleased/released are either (I would think they describe what I'd call "publish", but that's obviously a separate event)
    types: [published, unpublished, created, edited, deleted, prereleased, released]
jobs:
  do-release:
    runs-on: ubuntu-latest
    steps:
      - name: Print release info
        run: |
          echo "github.ref = ${{github.ref}}"
          echo "github.event_name = ${{github.event_name}}"
          echo "github.event.action = ${{github.event.action}}"
          echo "github.event.release.tag_name = ${{github.event.release.tag_name}}"
          echo "github.event.release.name = ${{github.event.release.name}}"
          echo "github.event.release.upload_url = ${{github.event.release.upload_url}}"
  publish-release:
    #environment: TestEnvironment
    if: github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
    - name: Test getting the release URL in a GitHub script
      uses: actions/github-script@v3
      with:
        user-agent: actions/github-script for ${{github.repository}}
        script: console.log(context);
    - name: Create test file
      run: |
        echo "Hello, world! ${{github.event.release.name}}" > test.txt
        echo "The other file! ${{github.event.release.name}}" > test2.txt
    - name: Upload test file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{github.event.release.upload_url}}
        asset_path: ./test.txt
        asset_name: test-uploadaction.txt
        asset_content_type: text/plain
    - name: Upload test files
      uses: actions/github-script@v3
      with:
        #github-token: ${{secrets.GITHUB_TOKEN}}
        user-agent: actions/github-script for ${{github.repository}}
        script: |
          const fs = require('fs').promises;
          const path = require('path');

          for (let filePath of await fs.readdir('.')) {
            const fileExtension = path.extname(filePath);
            if (fileExtension != '.txt') {
              continue;
            }

            console.log(`Uploading '${filePath}'`);
            const contentLength = (await fs.stat(filePath)).size;
            const fileContents = await fs.readFile(filePath);
            await github.repos.uploadReleaseAsset({
              url: '${{github.event.release.upload_url}}',
              headers: {
                'content-type': 'application/octet-stream',
                'content-length': contentLength
              },
              name: path.basename(filePath),
              data: fileContents
            });
          }
