name: Release Event Test
on:
  release:
    # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release
    # Seems `created` doesn't work here or it's not what I think it is
    # -- Oh!
    # > Note: The release event is not triggered for draft releases.
    # Emphasis on ****release event****, I read this as meaning to be the "released" type.
    # `created` will fire if you create a release and publish immediately without making it a draft first.
    #####################
    # Edited works!
    # Not sure how to trigger unpublished...
    # Deleted works
    # `released` (and probably `prereleased`) seem to only happen if you publish immediately without making a draft first.
    #types: [published, unpublished, created, edited, deleted, prereleased, released]
    types: [published]
jobs:
  do-release:
    runs-on: ubuntu-latest
    steps:
      - name: Print release info
        run: |
          echo "github.ref = ${{github.ref}}"
          echo "github.event_name = ${{github.event_name}}"
          echo "github.event.action = ${{github.event.action}}"
          echo "github.event.release.tag_name = ${{github.event.release.tag_name}}"
          echo "github.event.release.name = ${{github.event.release.name}}"
          echo "github.event.release.upload_url = ${{github.event.release.upload_url}}"
  publish-release:
    #environment: TestEnvironment
    if: github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test getting the release URL in a GitHub script
      uses: actions/github-script@v3
      with:
        user-agent: actions/github-script for ${{github.repository}}
        script: console.log(context);
    - name: Create test file
      run: |
        echo "Hello, world! ${{github.event.release.name}}" > test.txt
        echo "The other file! ${{github.event.release.name}}" > test2.txt
    - name: Upload test file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{github.event.release.upload_url}}
        asset_path: ./test.txt
        asset_name: test-uploadaction.txt
        asset_content_type: text/plain
    - name: Upload test files
      uses: actions/github-script@v4
      with:
        #github-token: ${{secrets.GITHUB_TOKEN}}
        user-agent: actions/github-script for ${{github.repository}}
        script: await require('./.github/workflows/upload-release-assets.js')(github, context);
