# Sadly this does not work :(
name: Run w/ inputs
on:
  push:
  workflow_dispatch:
jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "'$INPUT_TEST-INPUT'"
        with:
          test-input: Lol
