# I encountered an issue where my sccache cache on Windows was failing due to the log file being locked by the sccache server
# This tests my fix for it
name: Test fix for sccache caching of log bug
on: [push, workflow_dispatch]
jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      # ----------------------------------------------------------------------- Checkout
      - name: Checkout
        # We intentionally don't checkout submodules here
        # They will be restored as needed only if we need to build LLVM.
        uses: actions/checkout@v2

      # ----------------------------------------------------------------------- Setup Python
      - name: Setup Python 3.8
        if: matrix.skip-python-install != true
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # ----------------------------------------------------------------------- Install sccache
      # (This is necessary because we need the location used for the cache root later on)
      - name: Install sccache
        id: sccache
        run: python .github/workflows/install-sccache.py

      # ----------------------------------------------------------------------- Warm sccache cache
      - name: Load LLVM sccache
        id: cached-sccache
        # Always save the (potentially partial) sccache database so it can be used to accelerate subsequent builds when an intermittent failure occurs
        if: steps.cached-llvm.outputs.cache-hit != 'true' && always()
        uses: actions/cache@v2
        # If you change this configuration make sure to update keep-cache-warm.yml as well.
        with:
          path: |
            ${{steps.sccache.outputs.root-directory}}
            !${{steps.sccache.outputs.log-file-path}}
          key: sccache-cache-${{github.run_number}}

      - name: Start sccache server
        if: steps.cached-llvm.outputs.cache-hit != 'true'
        run: sccache --start-server

      - name: Show sccache statistics
        if: steps.cached-llvm.outputs.cache-hit != 'true' && always()
        run: |
          sccache --show-stats 2>&1 | tee ${{steps.sccache.outputs.root-directory}}/sccache-stats.txt
          #sccache --stop-server
