name: Scheduled test
on:
  schedule:
    # Every hour
    - cron: '0 * * * *'
    # Every 10 minutes
    - cron: '*/10 * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo Hello!
