name: Send CI Failure Notification
on:
  push:
  workflow_dispatch:
jobs:
  fake-job:
    strategy:
      fail-fast: false
      matrix:
        configuration: ['Debug', 'Release']
        command: ['true', 'false']
    name: Fake ${{matrix.configuration}}
    runs-on: ubuntu-latest
    steps:
      - name: failure
        run: ${{matrix.command}}
  send-notification:
    needs: fake-job
    if: failure()
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      # ----------------------------------------------------------------------- Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # ----------------------------------------------------------------------- Setup Python
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # ----------------------------------------------------------------------- Send failure
      - name: Send CI Failure Notification
        run: python .github/workflows/send-ci-failure-notification.py
        env:
          webhook_url: ${{secrets.TEAMS_WEBHOOK_URL}}
          github_organization: ${{github.repository_owner}}
          github_repo: ${{github.repository}}
          github_workflow_name: ${{github.workflow}}
          github_run_number: ${{github.run_id}}

