name: Allow .NET SDK welcome, but no certificate
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.7.20366.6
    - name: Run dotnet
      run: dotnet build
