name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  example_job:
    name: Greet user
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, ${{inputs.username}}
  another_job:
    name: Goodbye
    runs-on: ubuntu-latest
    steps:
      - run: echo Bye, ${{inputs.username}}
