name: Upload release assets Mochi.PhysX test
on: [release]
jobs:
  publish-release-assets:
    name: Publish Release Assets
    runs-on: ubuntu-latest
    #needs: build-mochi-physx
    if: github.event_name == 'release'
    steps:
      # ----------------------------------------------------------------------- Download all artifacts
      - name: Download artifacts
        run: |
          echo "Hello A" > A.txt
          mkdir FolderB
          echo "Hello B" > FolderB/B.txt

      # ----------------------------------------------------------------------- Upload release assets
      - name: Upload release assets
        uses: actions/github-script@v4
        with:
          user-agent: actions/github-script for ${{github.repository}}
          script: |
            const fs = require('fs').promises;
            const path = require('path');
            const uploadUrl = context.payload.release.upload_url;
            
            if (!uploadUrl) {
              throw "Missing release asset upload URL!";
            }

            async function uploadAssets(directoryPath) {
              for (let filePath of await fs.readdir(directoryPath)) {
                filePath = path.join(directoryPath, filePath);
                const stats = await fs.stat(filePath);

                if (stats.isDirectory()) {
                  console.log(`Entering '${filePath}'`);
                  await uploadAssets(filePath);
                  continue;
                }

                console.log(`Uploading '${filePath}'`);
                await github.repos.uploadReleaseAsset({
                  url: uploadUrl,
                  headers: {
                    'content-type': 'application/octet-stream',
                    'content-length': stats.size
                  },
                  name: path.basename(filePath),
                  data: await fs.readFile(filePath)
                });
              }
            }

            await uploadAssets('.');
