on: [workflow_dispatch]
jobs:
  vswhere:
    runs-on: windows-latest
    steps:
      - run: vswhere
      - run: |
          $devenv = vswhere -find Common7\IDE\devenv.com
          & $devenv /?