name: Who am I?
on: [workflow_dispatch]
jobs:
  whoami:
    runs-on: ubuntu-latest
    steps:
    - name: Who am I?
      run: whoami
    - name: Where am I?
      run: pwd
    - name: Look around...
      run: ls -la /home/runner
    - name: Look around more...
      run: ls -la /home/runner/runners
    - name: Look around even more...
      run: ps aux
