name: workflow_run sink
on:
  workflow_run:
    # This cannot be the file name, it must be the display name :/
    workflows: ["workflow_run source"]
    types: ["completed"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: cat <<< "$heck"
        env:
          heck: ${{toJSON(github.event)}}
      # I was wondering why this example here uses actions/github-scripts
      # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#using-data-from-the-triggering-workflow
      # And it turns out that stupid download-artifact ignores the run-id unless you explicitly provide a token
      # https://github.com/actions/download-artifact/blob/d3f86a106a0bac45b974a628896c90dbdf5c8093/src/download-artifact.ts#L53
      # We can just manually specify our token though, the documentation of download-artifact says it defaults to the run token but it doesn't actually
      - uses: actions/download-artifact@v4
        with:
          run-id: ${{github.event.workflow_run.id}}
          name: test-artifact
          github-token: ${{github.token}}
      - run: cat output.txt
